# Generated by Django 5.2.7 on 2025-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='slug',
        ),
        migrations.AddField(
            model_name='todotask',
            name='status',
            field=models.BooleanField(choices=[(False, 'В процессе'), (True, 'Сделано')], default=0, verbose_name='Статус'),
        ),
    ]
